-- Add birth chart columns to free_forecasts table
ALTER TABLE public.free_forecasts
ADD COLUMN IF NOT EXISTS moon_sign TEXT,
ADD COLUMN IF NOT EXISTS moon_sign_id INTEGER,
ADD COLUMN IF NOT EXISTS rising_sign TEXT,
ADD COLUMN IF NOT EXISTS rising_sign_id INTEGER,
ADD COLUMN IF NOT EXISTS sun_sign TEXT,
ADD COLUMN IF NOT EXISTS sun_sign_id INTEGER,
ADD COLUMN IF NOT EXISTS nakshatra TEXT,
ADD COLUMN IF NOT EXISTS nakshatra_id INTEGER,
ADD COLUMN IF NOT EXISTS nakshatra_pada INTEGER,
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;