-- Remove existing nakshatra records
DELETE FROM nakshatra_pressure_lookup;

-- Insert new comprehensive nakshatra data
INSERT INTO nakshatra_pressure_lookup (nakshatra, intensity_reason, moral_cost_limit, strain_accumulation, summary_interpretation) VALUES
('Ashwini', 'Under pressure, acts immediately without planning. Becomes more impulsive and scattered. May rush into solutions that create new problems. Can''t sit still with discomfort.', 'Will not tolerate being slowed down or held back indefinitely. Cannot maintain patience with bureaucracy or unnecessary delays. Loses interest once the initial excitement fades.', 'When overwhelmed, jumps from one thing to another without completing anything. Becomes restless, irritable, and accident-prone. May make rash decisions to escape the feeling of being trapped.', 'Fast-moving pioneer energy. Takes initiative quickly without overthinking. First to try new things. Impatient but courageous. Healing and helping nature. Child-like enthusiasm. Starts things brilliantly but struggles with follow-through.'),

('Bharani', 'Under pressure, becomes more controlling and rigid. Takes on even more responsibility. Can become judgmental of those who don''t meet their standards. Intensity turns inward as self-punishment.', 'Will not abandon responsibilities even when it''s destroying them. Cannot tolerate watching others suffer without intervening. Reaches breaking point when forced to be irresponsible or careless.', 'When overwhelmed, becomes resentful and bitter about carrying so much. May explode in anger after long suppression. Physical body often shows strain through tension and exhaustion.', 'Intense understanding of life, death, and transformation. Carries heavy responsibilities naturally. Strong sense of duty and restraint. Can bear what others cannot. Understands sacrifice. Often mature beyond years. Deals with endings and beginnings.'),

('Krittika', 'Under pressure, becomes more critical and cutting. Words become weapons. Perfectionism intensifies. May lash out at perceived incompetence. The inner critic becomes harsh and unforgiving.', 'Will not accept mediocrity or half-efforts when excellence is possible. Cannot tolerate continued mistakes when the solution is obvious. Loses patience with excuses.', 'When overwhelmed, either withdraws in disgust or unleashes harsh criticism. May cut people out suddenly. Becomes exhausted from holding everyone to impossible standards, including self.', 'Sharp, cutting, purifying energy. Sees what needs to be removed or changed. Direct and sometimes blunt. High standards and expectations. Natural critic with keen perception. Can be nurturing but demands excellence. Uses fire to burn away impurities.'),

('Rohini', 'Under pressure, clings harder to what''s familiar. Becomes more possessive and resistant to change. May use charm manipulatively. Seeks comfort through material security or relationships.', 'Will not easily let go of what brings security, even when it''s no longer serving them. Cannot tolerate instability or chaos for long. Needs tangible beauty and comfort to function.', 'When overwhelmed, retreats into comfort habits (food, shopping, security). May become stubborn and immovable. Can develop attachment issues. Holds on too long to relationships or situations.', 'Naturally magnetic and creative. Drawn to beauty, comfort, and pleasure. Strong aesthetic sense. Loyal and devoted. Values stability and security. Sensual and grounded. Can be possessive. Growth requires leaving comfort zones. Nurturing nature.'),

('Mrigashira', 'Under pressure, searches more frantically. Mental activity increases. Becomes flighty and hard to reach. May scatter energy across too many interests. The search becomes endless and unsatisfying.', 'Will not commit to something that feels too confining or final. Cannot settle when the feeling of ''something more'' persists. Needs mental stimulation and variety to thrive.', 'When overwhelmed, escapes into new interests or fantasies. Avoids commitment by always searching for the next thing. May appear superficial or unreliable. Mental exhaustion from constant seeking.', 'Searching, seeking, curious nature. Always looking for something more or different. Gentle but restless. Intellectual and mentally active. Can be elusive or hard to pin down. Loves the chase more than the catch. Innocent and playful quality.'),

('Ardra', 'Under pressure, becomes more intense and uncompromising. Emotional storms intensify. May become destructive to clear the way for truth. Analytical ability sharpens into criticism. Tears things apart to understand them.', 'Will not participate in anything false or surface-level once truth is glimpsed. Cannot maintain pretense for social comfort. Must express what''s real regardless of consequences.', 'When overwhelmed, creates chaos to match internal state. May become cold and cutting. Isolates after emotional storms. Can be destructive toward self or others. Exhaustion after intense periods.', 'Storm energy - destructive but cleansing. Emotional intensity and depth. Intellectual and analytical. Understands suffering and transformation. Can be harsh or ruthless in pursuit of truth. Sharp mind that cuts through illusions. Renewal after destruction.'),

('Punarvasu', 'Under pressure, maintains optimism but may become overly philosophical or detached. Seeks meaning in suffering. May escape into beliefs or ideas. Generosity continues even when it shouldn''t.', 'Will not stay in situations that restrict freedom or growth indefinitely. Cannot abandon hope or belief in better possibilities. Needs room to expand and explore.', 'When overwhelmed, escapes physically or mentally. May become restless and unable to settle. Over-extends through excessive generosity. Exhaustion from trying to maintain optimism in harsh circumstances.', 'Return of the light. Renewable energy and optimism. Philosophical and expansive. Can rebuild after loss. Generous and forgiving nature. Needs freedom and space. Often has multiple homes or interests. Jupiter''s wisdom and beneficence.'),

('Pushya', 'Under pressure, gives even more. Becomes over-responsible for others'' wellbeing. May martyr self. Traditional structures and rules become more important. Support becomes enabling.', 'Will not turn away from those who need help. Cannot abandon traditional values or duties even when personal cost is high. Must maintain order and stability.', 'When overwhelmed, becomes resentful of being taken for granted. May develop physical exhaustion from over-giving. Feels trapped by own sense of duty. Can become rigid about rules and tradition.', 'Nourishing, supportive, nurturing energy. Creates stability and security for others. Traditional values. Respects authority and structure. Devoted and caring. Can sacrifice self for others. Builds and maintains. Often in service or support roles.'),

('Ashlesha', 'Under pressure, becomes more controlling and manipulative. Psychological insight turns into weaponized understanding. May use guilt or emotional leverage. Grip tightens on what''s valued.', 'Will not trust easily or fully. Cannot be vulnerable without testing the other first. Must maintain some control over situations and relationships. Needs power to feel safe.', 'When overwhelmed, becomes paranoid about others'' motives. May strike preemptively. Isolates due to inability to trust. Can become entangled in own psychological games. Exhaustion from constant vigilance.', 'Penetrating, hypnotic, mysterious energy. Sees hidden motives and power dynamics. Can manipulate or control. Deeply psychological understanding. Protective but can be cunning. Coils around what it values. Transformative through intimate entanglement.'),

('Magha', 'Under pressure, becomes more demanding of respect and recognition. Pride increases. May become authoritarian or condescending. Ancestral or family pride becomes defensive. Status consciousness intensifies.', 'Will not accept disrespect or being treated as ordinary. Cannot diminish self or accomplishments for others'' comfort. Must maintain dignity and honor even at cost.', 'When overwhelmed, becomes isolated by own pride. May burn bridges over perceived slights. Exhaustion from maintaining regal bearing. Can become bitter if recognition doesn''t come.', 'Royal, regal, ancestral energy. Natural authority and dignity. Connected to lineage and legacy. Takes pride in accomplishments and status. Leadership qualities. Can be arrogant or entitled. Respects hierarchy. Wants to be recognized and honored.'),

('Purva Phalguni', 'Under pressure, seeks more pleasure or distraction. May become more self-indulgent or demanding of attention. Creativity can turn to performance. Need for recognition intensifies. Rest becomes escape.', 'Will not tolerate joyless existence for long. Cannot maintain effort without pleasure or reward. Must have beauty, comfort, and enjoyment to thrive. Needs appreciation and recognition.', 'When overwhelmed, escapes into pleasure or creativity. May overspend or over-indulge. Becomes demanding or dramatic when needs aren''t met. Exhaustion from performing or seeking validation.', 'Creative, pleasure-seeking, artistic energy. Loves beauty, luxury, and enjoyment. Generous and warm-hearted. Desires recognition and appreciation. Romantic and playful. Can be self-indulgent. Venus''s creative and relational energy. Needs rest and rejuvenation.'),

('Uttara Phalguni', 'Under pressure, becomes more rigid about commitments and obligations. Service to others intensifies. May become martyred in partnerships. Loyalty becomes inflexibility. Standards for self and others increase.', 'Will not break commitments or contracts even when they become harmful. Cannot abandon partnerships easily. Must maintain integrity even at personal cost. Needs clear agreements and structures.', 'When overwhelmed, feels trapped by own commitments. Resentment builds toward those served. May become rigid and inflexible. Exhaustion from carrying relationships or obligations alone.', 'Loyal, committed, partnership-oriented energy. Strong sense of integrity and contracts. Helpful and service-oriented. Values long-term relationships. Responsible and reliable. Can be rigid about commitments. Sun''s steady, supportive energy. Builds lasting foundations.'),

('Hasta', 'Under pressure, tries to fix or control the situation through skill or cleverness. May manipulate to regain control. Detail focus narrows. Work and perfectionism increase. Hands-on involvement intensifies.', 'Will not accept being unskilled or incompetent. Cannot tolerate situations where their abilities don''t matter or work. Must maintain control through skill and cleverness.', 'When overwhelmed, becomes controlling and micromanaging. May manipulate situations or people. Exhaustion from trying to fix everything. Can become rigid about methods or processes.', 'Skillful, clever, dexterous energy. Good with hands and crafts. Practical intelligence. Can manifest ideas into reality. Sometimes manipulative or tricky. Seeks control through skill. Detail-oriented. Healing hands. Can fix or create almost anything.'),

('Chitra', 'Under pressure, focuses more on appearance and image. Creative vision becomes more fixed and critical. Perfectionism about beauty and form increases. May become more concerned with how things look than how they are.', 'Will not accept ugliness or sloppiness in self or environment. Cannot tolerate poor design or lack of aesthetic consideration. Must create or maintain beauty to feel at ease.', 'When overwhelmed, becomes obsessed with appearance or image. May sacrifice substance for style. Exhaustion from maintaining perfection. Can become critical and difficult to please.', 'Artistic, aesthetic, design-oriented energy. Creates beauty and form. Charismatic and attractive. Strong sense of personal style. Can be superficial or image-focused. Builds beautiful things. Architect of reality. Desires perfection in appearance and creation.'),

('Swati', 'Under pressure, becomes more detached and elusive. Need for independence intensifies. May scatter energy or become hard to pin down. Adaptability turns to avoidance. Freedom becomes isolation.', 'Will not tolerate confinement or control for long. Cannot commit to rigid structures indefinitely. Must maintain freedom of movement and choice. Needs space to breathe and explore.', 'When overwhelmed, disappears or becomes unreachable. May scatter attention across too many things. Exhaustion from constant adaptation. Can become isolated by own need for independence.', 'Independent, flexible, adaptable energy. Moves like wind - free and unbound. Diplomatic and balanced. Can bend without breaking. Needs freedom and space. Sometimes scattered or unfocused. Learns through experience. Sword that cuts with precision and independence.'),

('Vishakha', 'Under pressure, becomes more obsessive about goals. Competition intensifies. May sacrifice relationships or health for achievement. Focus narrows. Drive becomes compulsion. Can become ruthless in pursuit.', 'Will not give up on important goals even when cost is high. Cannot accept failure or defeat gracefully. Must achieve what''s been set as objective. Needs to win or succeed.', 'When overwhelmed, becomes obsessed with single goal at expense of everything else. May burn out from relentless drive. Relationships suffer from single-minded focus. Exhaustion from never being satisfied.', 'Driven, ambitious, goal-oriented energy. Single-minded pursuit of objectives. Can be obsessive or intense. Doesn''t give up easily. Competitive nature. Jupiter and Agni''s transformative fire. Will sacrifice much for achievement. Determined and focused.'),

('Anuradha', 'Under pressure, tests loyalties more intensely. Becomes more secretive or guarded. Devotion deepens but expectations of others increase. May become suspicious or paranoid about group dynamics.', 'Will not betray those to whom devotion has been given. Cannot maintain surface relationships without depth. Must have meaningful connection to thrive. Loyalty is non-negotiable.', 'When overwhelmed, becomes possessive in friendships. May test relationships destructively. Exhaustion from maintaining group harmony. Can become bitter if loyalty isn''t reciprocated.', 'Devotional, loyal, friendship-oriented energy. Builds deep connections. Balances individual needs with group harmony. Can be secretive or mysterious. Understands power through relationship. Saturn''s discipline with devotional sweetness. Hidden depths.'),

('Jyeshtha', 'Under pressure, becomes more controlling and authoritarian. Protective instinct intensifies. May become domineering. Pride and ego swell. Takes on more responsibility. Control needs increase for security.', 'Will not relinquish control or authority easily. Cannot tolerate being powerless or unimportant. Must protect and guide others even when exhausting. Power is equated with safety.', 'When overwhelmed, becomes tyrannical or overbearing. May alienate others through need for control. Exhaustion from carrying everyone. Can become paranoid about threats to authority or position.', 'Elder, authority, protective energy. Takes responsibility for others. Can be controlling or dominating. Natural leader but also carries burden. Indra''s power and pride. Protects territory and those under care. Can be arrogant. Understands power dynamics deeply.'),

('Mula', 'Under pressure, tears things apart more aggressively. Questions become attacks. Destructive tendency increases. May burn everything down to find truth. Detachment becomes coldness. Revolutionary spirit intensifies.', 'Will not maintain structures or beliefs once seen as false. Cannot live with lies or pretense. Must get to root and truth regardless of cost. Destruction is sometimes necessary.', 'When overwhelmed, becomes destructive toward self or others. May create chaos. Isolation from questioning everything. Exhaustion from constant upheaval. Can lose direction after destroying foundations.', 'Root energy - gets to foundation of things. Destroys to rebuild. Philosophical and truth-seeking. Can be destructive or chaotic. Ketu''s detachment with Goddess Nirrti''s destruction. Questions everything. Uncompromising in pursuit of truth. Revolutionary.'),

('Purva Ashadha', 'Under pressure, confidence may turn to arrogance or denial. Refuses to acknowledge difficulty. Inspirational quality becomes forced positivity. Need to win intensifies. May take unnecessary risks.', 'Will not accept defeat or give up on victory. Cannot maintain pessimism or negativity for long. Must believe in success and positive outcome. Defeat is not an option in identity.', 'When overwhelmed, maintains false confidence to breaking point. May crash when reality hits. Exhaustion from forced optimism. Can become reckless in pursuit of victory.', 'Invincible, unconquerable energy. Confident and optimistic. Desires victory and success. Venus and water''s purifying, uplifting quality. Can be proud or overconfident. Inspirational and motivational. Believes in triumph. Won''t accept defeat.'),

('Uttara Ashadha', 'Under pressure, becomes more rigid about principles and goals. Ambition intensifies. May become more authoritarian or demanding. Standards for self and others increase. Need for lasting impact grows.', 'Will not compromise core principles for temporary gain. Cannot abandon quest for lasting achievement. Must build something permanent and meaningful. Righteousness is non-negotiable.', 'When overwhelmed, becomes inflexible and uncompromising. May alienate others with rigidity. Exhaustion from maintaining high standards. Can become bitter if lasting success doesn''t manifest.', 'Final victory, lasting achievement energy. Ambitious and determined. Leadership with responsibility. Universal consciousness. Sun gods'' righteous authority. Desires permanent success and recognition. Can be rigid or authoritarian. Builds lasting monuments.'),

('Shravana', 'Under pressure, listens and observes more carefully. Information gathering intensifies. May become more strategic or calculating. Diplomatic quality can turn manipulative. Network-building becomes survival strategy.', 'Will not act without adequate information. Cannot ignore what''s heard or known. Must listen and understand before deciding. Connection and communication are essential to function.', 'When overwhelmed, becomes paralyzed by too much information. May use knowledge manipulatively. Exhaustion from constant listening and awareness. Can become gossip or spread information harmfully.', 'Listening, learning, connecting energy. Gathers information and wisdom. Diplomatic and aware. Understands through hearing and observing. Moon''s receptive quality. Can be strategic or calculating. Builds networks. Preserves and transmits knowledge.'),

('Dhanishtha', 'Under pressure, focuses more on achievement and accumulation. Drive for success intensifies. May become more rigid or mechanical in approach. Competition increases. Material security becomes more important.', 'Will not accept poverty or lack of achievement. Cannot tolerate being unsuccessful or unrecognized. Must accumulate wealth or status to feel secure. Recognition is crucial to identity.', 'When overwhelmed, becomes obsessed with success markers. May sacrifice relationships for achievement. Exhaustion from constant drive. Can become rigid and inflexible in methods.', 'Wealthy, accomplished, rhythmic energy. Desires success and recognition. Musical and rhythmic understanding. Can achieve material prosperity. Eight Vasus'' divine abundance. Sometimes inflexible or mechanical. Builds wealth and status. Goal-oriented.'),

('Shatabhisha', 'Under pressure, becomes more secretive and withdrawn. Mystical or healing interest intensifies. May become more unconventional or radical. Isolation increases. Hidden knowledge becomes more important.', 'Will not conform to conventional healing or understanding. Cannot ignore mystical or hidden dimensions. Must work in ways that others might not understand. Secrets must be kept.', 'When overwhelmed, isolates completely. May become paranoid or conspiratorial. Exhaustion from being misunderstood. Can lose touch with practical reality in pursuit of hidden truth.', 'Hundred healers energy. Secretive, mystical, healing. Understands hidden knowledge and healing arts. Rahu''s illusion with Varuna''s cosmic order. Can be isolated or misunderstood. Sees what others don''t. Heals through unconventional means. Revolutionary healer.'),

('Purva Bhadrapada', 'Under pressure, becomes more intense and uncompromising. Cuts away what''s false without regard for social niceties. Can be destructive when cornered. Transformative fire burns hotter. Extremes intensify.', 'Will not tolerate continued participation in something known to be false or harmful. Once sees through an illusion, cannot unsee it and will not pretend. Authenticity is non-negotiable.', 'When overwhelmed, withdraws completely and burns bridges. Goes through cycles of intense engagement followed by total retreat. Can appear harsh or cold during strain. Exhaustion from intensity.', 'Intense transformative energy. Sees through illusions easily. Drawn to depth and hidden truths. Can appear cynical but has profound wisdom. Experiences extremes. Comfortable with endings. Dual nature: worldly success AND spiritual seeking. Purification through fire.'),

('Uttara Bhadrapada', 'Under pressure, goes deeper inward. May become more withdrawn or contemplative. Patience can turn to stagnation. Depth becomes isolation. Wisdom becomes weight. Silence intensifies.', 'Will not compromise dharma or cosmic order for temporary gain. Cannot engage with superficiality indefinitely. Must maintain depth and meaning. Patience has limits but they''re deep.', 'When overwhelmed, withdraws into silence and depth. May become immobile or stuck. Exhaustion from carrying cosmic wisdom. Can become depressed from seeing too much truth.', 'Deep wisdom, patience, depth energy. Understands cosmic order and dharma. Saturn''s discipline with serpent''s depth. Can be slow-moving but profound. Connects to universal truth. Seeks depth over breadth. Patient and enduring. Foundation of cosmic wisdom.'),

('Revati', 'Under pressure, becomes more dreamy or escapist. Spiritual inclination intensifies. May lose connection to practical reality. Compassion can become enabling. Guidance becomes over-responsibility.', 'Will not abandon spiritual path or compassionate response. Cannot ignore suffering or those who need guidance. Must maintain connection to divine or transcendent. Completion is necessary.', 'When overwhelmed, escapes into spiritual or fantasy realms. May lose grounding in physical reality. Exhaustion from guiding others. Can become martyred in service or compassion.', 'Journey''s end, completion, transcendence energy. Gentle, compassionate, spiritually inclined. Guides others across thresholds. Mercury''s intelligence with Pushan''s nourishing guidance. Can be dreamy or impractical. Connects to divine realms. Completes cycles.');